#ifndef __DOROTHY_PLATFORM_OPLATFORMDEFINE_H__
#define __DOROTHY_PLATFORM_OPLATFORMDEFINE_H__

#define NS_DOROTHY_PLATFORM_BEGIN namespace Dorothy { namespace Platform {
#define NS_DOROTHY_PLATFORM_END }}

#endif // __DOROTHY_PLATFORM_OPLATFORMDEFINE_H__